// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQGM0DLkRV66GzHs-xGuK9Q_rbFfOaSgg',
    appId: '1:142191797777:web:cec4fa38ca0fc9abf3f3b0',
    messagingSenderId: '142191797777',
    projectId: 'staff-attendance-e959c',
    authDomain: 'staff-attendance-e959c.firebaseapp.com',
    storageBucket: 'staff-attendance-e959c.firebasestorage.app',
    measurementId: 'G-EK4SNPLENB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAavCHSUPHtjkEo-QjpDiJKEanRED6FTs',
    appId: '1:142191797777:android:09c5ef7183e56dfaf3f3b0',
    messagingSenderId: '142191797777',
    projectId: 'staff-attendance-e959c',
    storageBucket: 'staff-attendance-e959c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRRrMFbmJpQnp-exxrlq-f9-9sjXVVuWI',
    appId: '1:142191797777:ios:cb681faef4fe4f81f3f3b0',
    messagingSenderId: '142191797777',
    projectId: 'staff-attendance-e959c',
    storageBucket: 'staff-attendance-e959c.firebasestorage.app',
    iosBundleId: 'com.staff.attendace.staffAttendance',
  );
}
